export const departmentData = {
  heads: { name: 'Iskhod Council' },
  sec: { name: 'Security - Rangers' },
  bls: { name: 'Security - Blackshield' },
  med: { name: 'Vesalius-Andra Medical' },
  sci: { name: 'Vesalius-Andra Research' },
  chr: { name: 'Church of the Absolute' },
  sup: { name: 'Frontier Logistics' },
  eng: { name: 'Artificer Guild' },
  pro: { name: 'Prospectors' },
  civ: { name: 'Contractors' },
  srv: { name: 'Independent Contractors' },
  ind: { name: 'Independant' },
  gry: { name: 'Greyson Positronic' },
  ldg: { name: 'Lodge' },
  bot: { name: 'Silicon' },
  misc: { name: 'Miscellaneous' },
};
