name: Generate documentation
on:
  push:
    branches:
    - master
permissions:
  contents: read

jobs:
  generate_documentation:
    permissions:
      contents: write  # for JamesIves/github-pages-deploy-action to push changes in repo
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}
    runs-on: ubuntu-20.04
    concurrency: gen-docs
    steps:
      - uses: actions/checkout@v4
      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: ~/SpacemanDMM
          key: ${{ runner.os }}-spacemandmm-${{ secrets.CACHE_PURGE_KEY }}
      - name: Install SpacemanDMM
        run: bash tools/ci/install_spaceman_dmm.sh dmdoc
      - name: Generate documentation
        run: |
          ~/dmdoc
          touch dmdoc/.nojekyll
          echo codedocs.cev-eris.net > dmdoc/CNAME
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.7.2
        with:
          branch: gh-pages
          clean: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          single-commit: true
          folder: dmdoc


