name: Manual Compare Changelogs

on:
  workflow_dispatch:
    inputs:
      left_ref:
        description: "Left ref (e.g., upstream/master)"
        required: false
        default: "upstream/master"
      right_ref:
        description: "Right ref (e.g., original/master)"
        required: false
        default: "original/master"

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Add remotes for comparison
        run: |
          git remote add upstream https://github.com/epic-new-soj-thing/Sojourn-Iskhod.git || true
          git remote add original https://github.com/sojourn-13/sojourn-station.git || true
          git fetch --all --prune

      - name: Generate per-file diffs (prints index to logs)
        run: |
          python tools/generate_changelog.py \
            --left "${{ github.event.inputs.left_ref || 'upstream/master' }}" \
            --right "${{ github.event.inputs.right_ref || 'original/master' }}" \
            --per-file-out .changelog_diffs \
            > changelogs_compare.md

      - name: Generate two-way changelogs (heuristic)
        run: |
          python tools/generate_changelog.py --left "${{ github.event.inputs.left_ref || 'upstream/master' }}" --right "${{ github.event.inputs.right_ref || 'original/master' }}" > changelogs_compare.md

      - name: Compute merge-base and diffs
        id: diff
        run: |
          LEFT_REF="${{ github.event.inputs.left_ref || 'upstream/master' }}"
          RIGHT_REF="${{ github.event.inputs.right_ref || 'original/master' }}"
          MB=$(git merge-base "$LEFT_REF" "$RIGHT_REF")
          echo "merge-base=$MB" >> $GITHUB_OUTPUT
          git diff -U0 "$MB..$LEFT_REF" > left.diff || true
          git diff -U0 "$MB..$RIGHT_REF" > right.diff || true

      - name: Summarize LEFT with Copilot
        id: leftsum
        uses: github/copilot-actions-models/summary@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          model: gpt-4o-mini
          input-type: diff
          max-tokens: 20000
          prompt: |
            You are generating a human-friendly changelog from a unified diff.
            - Group changes by file with concise bullet points of actual changes.
            - Prefer function/proc/define/constant names when present.
            - Use player-facing phrasing when applicable.
            - Output only markdown without backticks. Include a :cl: block.
          file-path: left.diff

      - name: Summarize RIGHT with Copilot
        id: rightsum
        uses: github/copilot-actions-models/summary@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          model: gpt-4o-mini
          input-type: diff
          max-tokens: 20000
          prompt: |
            You are generating a human-friendly changelog from a unified diff.
            - Group changes by file with concise bullet points of actual changes.
            - Prefer function/proc/define/constant names when present.
            - Use player-facing phrasing when applicable.
            - Output only markdown without backticks. Include a :cl: block.
          file-path: right.diff

      - name: Assemble Copilot report
        run: |
          {
            echo "# Copilot-based Cross-Repo Changelogs";
            echo;
            echo "## Left: ${{ github.event.inputs.left_ref || 'upstream/master' }} (vs ${{ github.event.inputs.right_ref || 'original/master' }})";
            echo;
            echo "${{ steps.leftsum.outputs.summary }}";
            echo;
            echo "## Right: ${{ github.event.inputs.right_ref || 'original/master' }} (vs ${{ github.event.inputs.left_ref || 'upstream/master' }})";
            echo;
            echo "${{ steps.rightsum.outputs.summary }}";
          } > changelogs_copilot.md

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: manual-compare-changelogs
          path: |
            changelogs_compare.md
            changelogs_copilot.md
            .changelog_diffs/**


